# Build-StockGlassesVisible.ps1 — generate StockGlassesVisible.AGF
#
# Scans stock-lens-catalog.sqlite for all distinct glasses used by
# NON-ASPHERIC SINGLETS. For each one, locates its source-AGF entry
# (across SCHOTT, OHARA, HOYA, SUMITA, CDGM, LIGHTPATH, CORNING_FS,
# CORNING_B, MISC) and copies the full multi-line entry (NM + ED + CD
# + TD + OD + LD + IT + CC lines through the next NM or EOF) into a
# new filtered AGF at catalogs/FilteredGlassCatalogues/StockGlassesVisible.AGF.
#
# Materials with import_status `NOT FOUND` in the SQLite are skipped
# (IR-only materials we don't have AGFs for).
#
# Idempotent — overwrites the output file on every run.

[CmdletBinding()]
param(
    [string]$DbPath = "$PSScriptRoot\..\stock-lens-catalog.sqlite",
    [string]$GlassDir = "$PSScriptRoot\..\Glass",
    [string]$OutFile = "$PSScriptRoot\..\FilteredGlassCatalogues\StockGlassesVisible.AGF"
)

Import-Module PSSQLite -ErrorAction Stop

# ── 1. Query SQLite for the distinct glasses we need ───────────────────────
$query = @'
SELECT DISTINCT ls.glass_name
FROM lens_surfaces ls
JOIN stock_lenses s ON s.vendor = ls.vendor AND s.part_number = ls.part_number
WHERE s.n_elements = 1
  AND ls.glass_name IS NOT NULL
  AND ls.glass_name != ''
  AND ls.glass_catalog != 'NOT FOUND'
  AND NOT EXISTS (
    SELECT 1 FROM lens_surfaces ls2
    WHERE ls2.vendor = s.vendor AND ls2.part_number = s.part_number
      AND ls2.surface_type NOT IN ('STANDARD', 'Standard')
  )
ORDER BY ls.glass_name;
'@

$rows = Invoke-SqliteQuery -DataSource $DbPath -Query $query
$wanted = $rows | ForEach-Object { $_.glass_name } | Sort-Object -Unique
Write-Host "Wanted distinct glasses (non-aspheric singlets): $($wanted.Count)"

# ── 2. Index every NM entry across all vendor AGFs ─────────────────────────
# Each AGF is line-based; an entry starts at `NM <NAME> ...` and continues
# until the next `NM` line or EOF. Capture the line range so we can copy
# the full entry verbatim.

$agfFiles = Get-ChildItem -Path $GlassDir -Filter '*.AGF' -File |
            Where-Object { $_.Name -notlike '*.bak' }

$index = @{}  # glassName -> [PSCustomObject]@{File, StartLine, EndLine, Lines}

foreach ($agf in $agfFiles) {
    # CDGM is UTF-16LE, others are ASCII/UTF-8. AGFs are small so just
    # let Get-Content sniff via -Encoding default vs explicit unicode.
    $lines = if ($agf.Name -eq 'CDGM.AGF') {
        Get-Content -Path $agf.FullName -Encoding Unicode
    } else {
        Get-Content -Path $agf.FullName -Encoding UTF8
    }

    $currentName = $null
    $currentStart = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line -match '^NM\s+(\S+)') {
            if ($currentName -ne $null) {
                # Close out previous entry
                $entry = [PSCustomObject]@{
                    File      = $agf.Name
                    StartLine = $currentStart
                    EndLine   = $i - 1
                    Lines     = $lines[$currentStart..($i-1)]
                }
                if (-not $index.ContainsKey($currentName)) {
                    $index[$currentName] = $entry
                }
            }
            $currentName = $matches[1]
            $currentStart = $i
        }
    }
    # Final entry
    if ($currentName -ne $null) {
        $entry = [PSCustomObject]@{
            File      = $agf.Name
            StartLine = $currentStart
            EndLine   = $lines.Count - 1
            Lines     = $lines[$currentStart..($lines.Count-1)]
        }
        if (-not $index.ContainsKey($currentName)) {
            $index[$currentName] = $entry
        }
    }
}

Write-Host "Indexed $($index.Count) total glass entries across $($agfFiles.Count) AGF files"

# ── 3. Resolve each wanted glass; collect entries + log misses ─────────────
$out = New-Object System.Collections.Generic.List[string]
$resolved = 0
$missing  = @()

$out.Add('CC ============================================================================')
$out.Add('CC StockGlassesVisible.AGF — Filtered glass catalog for visible-spectrum')
$out.Add('CC stock-lens optimization')
$out.Add('CC ============================================================================')
$out.Add('CC')
$out.Add('CC Generated by catalogs/scripts/Build-StockGlassesVisible.ps1')
$out.Add('CC Source: catalogs/stock-lens-catalog.sqlite (non-aspheric singlets across')
$out.Add('CC Edmund + Thorlabs + Ross Optical)')
$out.Add(('CC Generated: ' + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')))
$out.Add('CC')
$out.Add('CC Picked automatically by `set_stock_glass_substitution` when')
$out.Add('CC min(system.Wavelengths) >= 0.380 microns.')
$out.Add('CC ============================================================================')
$out.Add('')

foreach ($name in $wanted) {
    if ($index.ContainsKey($name)) {
        $entry = $index[$name]
        $out.Add(('CC ---------------- ' + $name + ' (from ' + $entry.File + ') -----'))
        foreach ($l in $entry.Lines) { $out.Add($l) }
        $out.Add('')
        $resolved++
    } else {
        $missing += $name
    }
}

# ── 4. Write the output file ───────────────────────────────────────────────
$outDir = Split-Path -Parent $OutFile
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }
Set-Content -Path $OutFile -Value $out -Encoding UTF8

Write-Host ""
Write-Host "Wrote: $OutFile"
Write-Host "  Resolved: $resolved / $($wanted.Count)"
if ($missing.Count -gt 0) {
    Write-Host "  Missing (not found in any AGF): $($missing -join ', ')"
}
